name: SynMall
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.12
  - pandas=2.2.3
  - numpy=2.2.6
  - joblib=1.5.1
  - pyyaml=6.0.2
  - scikit-learn=1.6.1
  - matplotlib=3.10.3
  - lightgbm=4.6.0
  - tqdm=4.67.1
  - adjusttext=1.3.0
  - scipy=1.15.2
  - statannotations=0.7.2
  - seaborn=0.13.2