boosting_type: gbdt
objective: binary
metric:
- binary_logloss
- auc
nthread: 4
is_unbalance: true
verbosity: -1
n_jobs: 4
num_leaves: 20
max_depth: 3
max_bin: 255
min_data_in_leaf: 30
feature_fraction: 0.75
bagging_fraction: 1.0
bagging_freq: 10
lambda_l1: 0.001
lambda_l2: 0.001
min_split_gain: 0.05
learning_rate: 0.1
